// Generated by gencpp from file suii_communication_ros1/TableGoalResponse.msg
// DO NOT EDIT!


#ifndef SUII_COMMUNICATION_ROS1_MESSAGE_TABLEGOALRESPONSE_H
#define SUII_COMMUNICATION_ROS1_MESSAGE_TABLEGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace suii_communication_ros1
{
template <class ContainerAllocator>
struct TableGoalResponse_
{
  typedef TableGoalResponse_<ContainerAllocator> Type;

  TableGoalResponse_()
    : succes(false)  {
    }
  TableGoalResponse_(const ContainerAllocator& _alloc)
    : succes(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succes_type;
  _succes_type succes;





  typedef boost::shared_ptr< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TableGoalResponse_

typedef ::suii_communication_ros1::TableGoalResponse_<std::allocator<void> > TableGoalResponse;

typedef boost::shared_ptr< ::suii_communication_ros1::TableGoalResponse > TableGoalResponsePtr;
typedef boost::shared_ptr< ::suii_communication_ros1::TableGoalResponse const> TableGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator1> & lhs, const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.succes == rhs.succes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator1> & lhs, const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace suii_communication_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "509793171e494962cd366ecf60e100e4";
  }

  static const char* value(const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x509793171e494962ULL;
  static const uint64_t static_value2 = 0xcd366ecf60e100e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "suii_communication_ros1/TableGoalResponse";
  }

  static const char* value(const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succes\n"
"\n"
;
  }

  static const char* value(const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TableGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::suii_communication_ros1::TableGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "succes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUII_COMMUNICATION_ROS1_MESSAGE_TABLEGOALRESPONSE_H
