// Generated by gencpp from file suii_communication_ros1/TableGoal.msg
// DO NOT EDIT!


#ifndef SUII_COMMUNICATION_ROS1_MESSAGE_TABLEGOAL_H
#define SUII_COMMUNICATION_ROS1_MESSAGE_TABLEGOAL_H

#include <ros/service_traits.h>


#include <suii_communication_ros1/TableGoalRequest.h>
#include <suii_communication_ros1/TableGoalResponse.h>


namespace suii_communication_ros1
{

struct TableGoal
{

typedef TableGoalRequest Request;
typedef TableGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TableGoal
} // namespace suii_communication_ros1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::suii_communication_ros1::TableGoal > {
  static const char* value()
  {
    return "65abe4d9d82c411cf962b85d02507ffe";
  }

  static const char* value(const ::suii_communication_ros1::TableGoal&) { return value(); }
};

template<>
struct DataType< ::suii_communication_ros1::TableGoal > {
  static const char* value()
  {
    return "suii_communication_ros1/TableGoal";
  }

  static const char* value(const ::suii_communication_ros1::TableGoal&) { return value(); }
};


// service_traits::MD5Sum< ::suii_communication_ros1::TableGoalRequest> should match
// service_traits::MD5Sum< ::suii_communication_ros1::TableGoal >
template<>
struct MD5Sum< ::suii_communication_ros1::TableGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::suii_communication_ros1::TableGoal >::value();
  }
  static const char* value(const ::suii_communication_ros1::TableGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::suii_communication_ros1::TableGoalRequest> should match
// service_traits::DataType< ::suii_communication_ros1::TableGoal >
template<>
struct DataType< ::suii_communication_ros1::TableGoalRequest>
{
  static const char* value()
  {
    return DataType< ::suii_communication_ros1::TableGoal >::value();
  }
  static const char* value(const ::suii_communication_ros1::TableGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::suii_communication_ros1::TableGoalResponse> should match
// service_traits::MD5Sum< ::suii_communication_ros1::TableGoal >
template<>
struct MD5Sum< ::suii_communication_ros1::TableGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::suii_communication_ros1::TableGoal >::value();
  }
  static const char* value(const ::suii_communication_ros1::TableGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::suii_communication_ros1::TableGoalResponse> should match
// service_traits::DataType< ::suii_communication_ros1::TableGoal >
template<>
struct DataType< ::suii_communication_ros1::TableGoalResponse>
{
  static const char* value()
  {
    return DataType< ::suii_communication_ros1::TableGoal >::value();
  }
  static const char* value(const ::suii_communication_ros1::TableGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUII_COMMUNICATION_ROS1_MESSAGE_TABLEGOAL_H
