// Generated by gencpp from file atwork_commander_msgs/Arena.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_ARENA_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_ARENA_H

#include <ros/service_traits.h>


#include <atwork_commander_msgs/ArenaRequest.h>
#include <atwork_commander_msgs/ArenaResponse.h>


namespace atwork_commander_msgs
{

struct Arena
{

typedef ArenaRequest Request;
typedef ArenaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Arena
} // namespace atwork_commander_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atwork_commander_msgs::Arena > {
  static const char* value()
  {
    return "7e66b1e503b6583890f0a58c451d85ab";
  }

  static const char* value(const ::atwork_commander_msgs::Arena&) { return value(); }
};

template<>
struct DataType< ::atwork_commander_msgs::Arena > {
  static const char* value()
  {
    return "atwork_commander_msgs/Arena";
  }

  static const char* value(const ::atwork_commander_msgs::Arena&) { return value(); }
};


// service_traits::MD5Sum< ::atwork_commander_msgs::ArenaRequest> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::Arena >
template<>
struct MD5Sum< ::atwork_commander_msgs::ArenaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::Arena >::value();
  }
  static const char* value(const ::atwork_commander_msgs::ArenaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::ArenaRequest> should match
// service_traits::DataType< ::atwork_commander_msgs::Arena >
template<>
struct DataType< ::atwork_commander_msgs::ArenaRequest>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::Arena >::value();
  }
  static const char* value(const ::atwork_commander_msgs::ArenaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atwork_commander_msgs::ArenaResponse> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::Arena >
template<>
struct MD5Sum< ::atwork_commander_msgs::ArenaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::Arena >::value();
  }
  static const char* value(const ::atwork_commander_msgs::ArenaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::ArenaResponse> should match
// service_traits::DataType< ::atwork_commander_msgs::Arena >
template<>
struct DataType< ::atwork_commander_msgs::ArenaResponse>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::Arena >::value();
  }
  static const char* value(const ::atwork_commander_msgs::ArenaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_ARENA_H
