// Generated by gencpp from file atwork_commander_msgs/ArenaResponse.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_ARENARESPONSE_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_ARENARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct ArenaResponse_
{
  typedef ArenaResponse_<ContainerAllocator> Type;

  ArenaResponse_()
    {
    }
  ArenaResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArenaResponse_

typedef ::atwork_commander_msgs::ArenaResponse_<std::allocator<void> > ArenaResponse;

typedef boost::shared_ptr< ::atwork_commander_msgs::ArenaResponse > ArenaResponsePtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::ArenaResponse const> ArenaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/ArenaResponse";
  }

  static const char* value(const ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"### response ###\n"
"\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArenaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::atwork_commander_msgs::ArenaResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_ARENARESPONSE_H
