// Generated by gencpp from file atwork_commander_msgs/GenerateTaskRequest.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_GENERATETASKREQUEST_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_GENERATETASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct GenerateTaskRequest_
{
  typedef GenerateTaskRequest_<ContainerAllocator> Type;

  GenerateTaskRequest_()
    : task_name()  {
    }
  GenerateTaskRequest_(const ContainerAllocator& _alloc)
    : task_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_name_type;
  _task_name_type task_name;





  typedef boost::shared_ptr< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTaskRequest_

typedef ::atwork_commander_msgs::GenerateTaskRequest_<std::allocator<void> > GenerateTaskRequest;

typedef boost::shared_ptr< ::atwork_commander_msgs::GenerateTaskRequest > GenerateTaskRequestPtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::GenerateTaskRequest const> GenerateTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_name == rhs.task_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfe37cdddcaaf5bd95f630c73751773b";
  }

  static const char* value(const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfe37cdddcaaf5bdULL;
  static const uint64_t static_value2 = 0x95f630c73751773bULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/GenerateTaskRequest";
  }

  static const char* value(const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_name\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atwork_commander_msgs::GenerateTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_GENERATETASKREQUEST_H
