// Generated by gencpp from file atwork_commander_msgs/GenerateTask.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_GENERATETASK_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_GENERATETASK_H

#include <ros/service_traits.h>


#include <atwork_commander_msgs/GenerateTaskRequest.h>
#include <atwork_commander_msgs/GenerateTaskResponse.h>


namespace atwork_commander_msgs
{

struct GenerateTask
{

typedef GenerateTaskRequest Request;
typedef GenerateTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateTask
} // namespace atwork_commander_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atwork_commander_msgs::GenerateTask > {
  static const char* value()
  {
    return "25819facc69a2e03b3944223830c0b17";
  }

  static const char* value(const ::atwork_commander_msgs::GenerateTask&) { return value(); }
};

template<>
struct DataType< ::atwork_commander_msgs::GenerateTask > {
  static const char* value()
  {
    return "atwork_commander_msgs/GenerateTask";
  }

  static const char* value(const ::atwork_commander_msgs::GenerateTask&) { return value(); }
};


// service_traits::MD5Sum< ::atwork_commander_msgs::GenerateTaskRequest> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::GenerateTask >
template<>
struct MD5Sum< ::atwork_commander_msgs::GenerateTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::GenerateTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::GenerateTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::GenerateTaskRequest> should match
// service_traits::DataType< ::atwork_commander_msgs::GenerateTask >
template<>
struct DataType< ::atwork_commander_msgs::GenerateTaskRequest>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::GenerateTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::GenerateTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atwork_commander_msgs::GenerateTaskResponse> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::GenerateTask >
template<>
struct MD5Sum< ::atwork_commander_msgs::GenerateTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::GenerateTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::GenerateTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::GenerateTaskResponse> should match
// service_traits::DataType< ::atwork_commander_msgs::GenerateTask >
template<>
struct DataType< ::atwork_commander_msgs::GenerateTaskResponse>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::GenerateTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::GenerateTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_GENERATETASK_H
