// Generated by gencpp from file atwork_commander_msgs/LoadTask.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_LOADTASK_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_LOADTASK_H

#include <ros/service_traits.h>


#include <atwork_commander_msgs/LoadTaskRequest.h>
#include <atwork_commander_msgs/LoadTaskResponse.h>


namespace atwork_commander_msgs
{

struct LoadTask
{

typedef LoadTaskRequest Request;
typedef LoadTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadTask
} // namespace atwork_commander_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atwork_commander_msgs::LoadTask > {
  static const char* value()
  {
    return "f94a92de0a9d926d38fa9af9eb8b4091";
  }

  static const char* value(const ::atwork_commander_msgs::LoadTask&) { return value(); }
};

template<>
struct DataType< ::atwork_commander_msgs::LoadTask > {
  static const char* value()
  {
    return "atwork_commander_msgs/LoadTask";
  }

  static const char* value(const ::atwork_commander_msgs::LoadTask&) { return value(); }
};


// service_traits::MD5Sum< ::atwork_commander_msgs::LoadTaskRequest> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::LoadTask >
template<>
struct MD5Sum< ::atwork_commander_msgs::LoadTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::LoadTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::LoadTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::LoadTaskRequest> should match
// service_traits::DataType< ::atwork_commander_msgs::LoadTask >
template<>
struct DataType< ::atwork_commander_msgs::LoadTaskRequest>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::LoadTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::LoadTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atwork_commander_msgs::LoadTaskResponse> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::LoadTask >
template<>
struct MD5Sum< ::atwork_commander_msgs::LoadTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::LoadTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::LoadTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::LoadTaskResponse> should match
// service_traits::DataType< ::atwork_commander_msgs::LoadTask >
template<>
struct DataType< ::atwork_commander_msgs::LoadTaskResponse>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::LoadTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::LoadTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_LOADTASK_H
