// Generated by gencpp from file atwork_commander_msgs/LoadTaskRequest.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_LOADTASKREQUEST_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_LOADTASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <atwork_commander_msgs/Task.h>

namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct LoadTaskRequest_
{
  typedef LoadTaskRequest_<ContainerAllocator> Type;

  LoadTaskRequest_()
    : task()  {
    }
  LoadTaskRequest_(const ContainerAllocator& _alloc)
    : task(_alloc)  {
  (void)_alloc;
    }



   typedef  ::atwork_commander_msgs::Task_<ContainerAllocator>  _task_type;
  _task_type task;





  typedef boost::shared_ptr< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadTaskRequest_

typedef ::atwork_commander_msgs::LoadTaskRequest_<std::allocator<void> > LoadTaskRequest;

typedef boost::shared_ptr< ::atwork_commander_msgs::LoadTaskRequest > LoadTaskRequestPtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::LoadTaskRequest const> LoadTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task == rhs.task;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "320ae3adc870aff0e94ed6fe1487ffbf";
  }

  static const char* value(const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x320ae3adc870aff0ULL;
  static const uint64_t static_value2 = 0xe94ed6fe1487ffbfULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/LoadTaskRequest";
  }

  static const char* value(const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Task task\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Task\n"
"# Task.msg\n"
"\n"
"RobotHeader[] execute_on\n"
"\n"
"Workstation[] arena_start_state\n"
"Workstation[] arena_target_state\n"
"\n"
"duration prep_time\n"
"duration exec_time\n"
"\n"
"string type\n"
"uint64 id\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/RobotHeader\n"
"# RobotHeader.msg\n"
"\n"
"Header header\n"
"string team_name\n"
"string robot_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Workstation\n"
"# workstation.msg\n"
"\n"
" Object[] objects\n"
"\n"
"# either a workstation name or 'robot'\n"
"# (for end of RTT or start of PPT)\n"
"string workstation_name\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Object\n"
"# Object.msg\n"
"\n"
"uint16 object\n"
"uint16 target\n"
"bool   decoy\n"
"\n"
"uint16 EMPTY = 0\n"
"\n"
"# atwork\n"
"uint16 ATWORK_START = 11\n"
"uint16 F20_20_B = 11\n"
"uint16 F20_20_G = 12\n"
"uint16 S40_40_B = 13\n"
"uint16 S40_40_G = 14\n"
"uint16 M20_100 = 15\n"
"uint16 M20 = 16\n"
"uint16 M30 = 17\n"
"uint16 R20 = 18\n"
"uint16 ATWORK_END = 19\n"
"\n"
"# rockin\n"
"uint16 ROCKIN_START = 21\n"
"uint16 BEARING_BOX = 21\n"
"uint16 BEARING = 22\n"
"uint16 AXIS = 23\n"
"uint16 DISTANCE_TUBE = 24\n"
"uint16 MOTOR = 25\n"
"uint16 ROCKIN_END = 26\n"
"\n"
"# container\n"
"uint16 CONTAINER_START = 31\n"
"uint16 CONTAINER_RED = 31\n"
"uint16 CONTAINER_BLUE = 32\n"
"uint16 CONTAINER_END = 33\n"
"\n"
"# cavity\n"
"uint16 CAVITY_START = 41\n"
"uint16 F20_20_H  = 41\n"
"uint16 F20_20_V  = 42\n"
"uint16 F20_20_F  = 43\n"
"uint16 S40_40_H  = 44\n"
"uint16 S40_40_V  = 45\n"
"uint16 S40_40_F  = 46\n"
"uint16 M20_H     = 47\n"
"uint16 M20_V     = 48\n"
"uint16 M20_F     = 49\n"
"uint16 M20_100_H = 50\n"
"uint16 M20_100_V = 51\n"
"uint16 M20_100_F = 52\n"
"uint16 M30_H     = 53\n"
"uint16 M30_V     = 54\n"
"uint16 M30_F     = 55\n"
"uint16 R20_H     = 56\n"
"uint16 R20_V     = 57\n"
"uint16 R20_F     = 58\n"
"uint16 CAVITY_END = 59\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atwork_commander_msgs::LoadTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    s << std::endl;
    Printer< ::atwork_commander_msgs::Task_<ContainerAllocator> >::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_LOADTASKREQUEST_H
