// Generated by gencpp from file atwork_commander_msgs/RobotState.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_ROBOTSTATE_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <atwork_commander_msgs/RobotHeader.h>
#include <geometry_msgs/Pose2D.h>
#include <nav_msgs/Path.h>
#include <atwork_commander_msgs/Object.h>
#include <atwork_commander_msgs/Workstation.h>

namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : sender()
    , pose()
    , path()
    , objects_on_robot()
    , current_arena_state()  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , pose(_alloc)
    , path(_alloc)
    , objects_on_robot()
    , current_arena_state(_alloc)  {
  (void)_alloc;
      objects_on_robot.assign( ::atwork_commander_msgs::Object_<ContainerAllocator> (_alloc));
  }



   typedef  ::atwork_commander_msgs::RobotHeader_<ContainerAllocator>  _sender_type;
  _sender_type sender;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef boost::array< ::atwork_commander_msgs::Object_<ContainerAllocator> , 3>  _objects_on_robot_type;
  _objects_on_robot_type objects_on_robot;

   typedef std::vector< ::atwork_commander_msgs::Workstation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::atwork_commander_msgs::Workstation_<ContainerAllocator> >::other >  _current_arena_state_type;
  _current_arena_state_type current_arena_state;





  typedef boost::shared_ptr< ::atwork_commander_msgs::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::atwork_commander_msgs::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::atwork_commander_msgs::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atwork_commander_msgs::RobotState_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::RobotState_<ContainerAllocator2> & rhs)
{
  return lhs.sender == rhs.sender &&
    lhs.pose == rhs.pose &&
    lhs.path == rhs.path &&
    lhs.objects_on_robot == rhs.objects_on_robot &&
    lhs.current_arena_state == rhs.current_arena_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atwork_commander_msgs::RobotState_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::RobotState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd883dda0c5739d8cae16aa5923663e5";
  }

  static const char* value(const ::atwork_commander_msgs::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd883dda0c5739d8ULL;
  static const uint64_t static_value2 = 0xcae16aa5923663e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/RobotState";
  }

  static const char* value(const ::atwork_commander_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotState.msg\n"
"\n"
"RobotHeader sender\n"
"\n"
"geometry_msgs/Pose2D pose\n"
"nav_msgs/Path path\n"
"\n"
"Object[3] objects_on_robot\n"
"Workstation[] current_arena_state\n"
"\n"
"\n"
"\n"
"# additional content for season 2021 or later (use markers?)\n"
"# TODO: datatype for barriertape\n"
"# TODO: datatype for obstacles\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/RobotHeader\n"
"# RobotHeader.msg\n"
"\n"
"Header header\n"
"string team_name\n"
"string robot_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Object\n"
"# Object.msg\n"
"\n"
"uint16 object\n"
"uint16 target\n"
"bool   decoy\n"
"\n"
"uint16 EMPTY = 0\n"
"\n"
"# atwork\n"
"uint16 ATWORK_START = 11\n"
"uint16 F20_20_B = 11\n"
"uint16 F20_20_G = 12\n"
"uint16 S40_40_B = 13\n"
"uint16 S40_40_G = 14\n"
"uint16 M20_100 = 15\n"
"uint16 M20 = 16\n"
"uint16 M30 = 17\n"
"uint16 R20 = 18\n"
"uint16 ATWORK_END = 19\n"
"\n"
"# rockin\n"
"uint16 ROCKIN_START = 21\n"
"uint16 BEARING_BOX = 21\n"
"uint16 BEARING = 22\n"
"uint16 AXIS = 23\n"
"uint16 DISTANCE_TUBE = 24\n"
"uint16 MOTOR = 25\n"
"uint16 ROCKIN_END = 26\n"
"\n"
"# container\n"
"uint16 CONTAINER_START = 31\n"
"uint16 CONTAINER_RED = 31\n"
"uint16 CONTAINER_BLUE = 32\n"
"uint16 CONTAINER_END = 33\n"
"\n"
"# cavity\n"
"uint16 CAVITY_START = 41\n"
"uint16 F20_20_H  = 41\n"
"uint16 F20_20_V  = 42\n"
"uint16 F20_20_F  = 43\n"
"uint16 S40_40_H  = 44\n"
"uint16 S40_40_V  = 45\n"
"uint16 S40_40_F  = 46\n"
"uint16 M20_H     = 47\n"
"uint16 M20_V     = 48\n"
"uint16 M20_F     = 49\n"
"uint16 M20_100_H = 50\n"
"uint16 M20_100_V = 51\n"
"uint16 M20_100_F = 52\n"
"uint16 M30_H     = 53\n"
"uint16 M30_V     = 54\n"
"uint16 M30_F     = 55\n"
"uint16 R20_H     = 56\n"
"uint16 R20_V     = 57\n"
"uint16 R20_F     = 58\n"
"uint16 CAVITY_END = 59\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Workstation\n"
"# workstation.msg\n"
"\n"
" Object[] objects\n"
"\n"
"# either a workstation name or 'robot'\n"
"# (for end of RTT or start of PPT)\n"
"string workstation_name\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.pose);
      stream.next(m.path);
      stream.next(m.objects_on_robot);
      stream.next(m.current_arena_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atwork_commander_msgs::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    s << std::endl;
    Printer< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.sender);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "objects_on_robot[]" << std::endl;
    for (size_t i = 0; i < v.objects_on_robot.size(); ++i)
    {
      s << indent << "  objects_on_robot[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::atwork_commander_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects_on_robot[i]);
    }
    s << indent << "current_arena_state[]" << std::endl;
    for (size_t i = 0; i < v.current_arena_state.size(); ++i)
    {
      s << indent << "  current_arena_state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::atwork_commander_msgs::Workstation_<ContainerAllocator> >::stream(s, indent + "    ", v.current_arena_state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_ROBOTSTATE_H
