// Generated by gencpp from file atwork_commander_msgs/RobotHeader.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_ROBOTHEADER_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_ROBOTHEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct RobotHeader_
{
  typedef RobotHeader_<ContainerAllocator> Type;

  RobotHeader_()
    : header()
    , team_name()
    , robot_name()  {
    }
  RobotHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , team_name(_alloc)
    , robot_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _team_name_type;
  _team_name_type team_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;





  typedef boost::shared_ptr< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> const> ConstPtr;

}; // struct RobotHeader_

typedef ::atwork_commander_msgs::RobotHeader_<std::allocator<void> > RobotHeader;

typedef boost::shared_ptr< ::atwork_commander_msgs::RobotHeader > RobotHeaderPtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::RobotHeader const> RobotHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.team_name == rhs.team_name &&
    lhs.robot_name == rhs.robot_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "094546f167b80c29553c27f3c3f6e642";
  }

  static const char* value(const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x094546f167b80c29ULL;
  static const uint64_t static_value2 = 0x553c27f3c3f6e642ULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/RobotHeader";
  }

  static const char* value(const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotHeader.msg\n"
"\n"
"Header header\n"
"string team_name\n"
"string robot_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.team_name);
      stream.next(m.robot_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atwork_commander_msgs::RobotHeader_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "team_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.team_name);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_ROBOTHEADER_H
