// Generated by gencpp from file atwork_commander_msgs/StartTask.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_STARTTASK_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_STARTTASK_H

#include <ros/service_traits.h>


#include <atwork_commander_msgs/StartTaskRequest.h>
#include <atwork_commander_msgs/StartTaskResponse.h>


namespace atwork_commander_msgs
{

struct StartTask
{

typedef StartTaskRequest Request;
typedef StartTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTask
} // namespace atwork_commander_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atwork_commander_msgs::StartTask > {
  static const char* value()
  {
    return "ce94f07cc50d671de45a7a3e85438361";
  }

  static const char* value(const ::atwork_commander_msgs::StartTask&) { return value(); }
};

template<>
struct DataType< ::atwork_commander_msgs::StartTask > {
  static const char* value()
  {
    return "atwork_commander_msgs/StartTask";
  }

  static const char* value(const ::atwork_commander_msgs::StartTask&) { return value(); }
};


// service_traits::MD5Sum< ::atwork_commander_msgs::StartTaskRequest> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::StartTask >
template<>
struct MD5Sum< ::atwork_commander_msgs::StartTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::StartTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::StartTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::StartTaskRequest> should match
// service_traits::DataType< ::atwork_commander_msgs::StartTask >
template<>
struct DataType< ::atwork_commander_msgs::StartTaskRequest>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::StartTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::StartTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atwork_commander_msgs::StartTaskResponse> should match
// service_traits::MD5Sum< ::atwork_commander_msgs::StartTask >
template<>
struct MD5Sum< ::atwork_commander_msgs::StartTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atwork_commander_msgs::StartTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::StartTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atwork_commander_msgs::StartTaskResponse> should match
// service_traits::DataType< ::atwork_commander_msgs::StartTask >
template<>
struct DataType< ::atwork_commander_msgs::StartTaskResponse>
{
  static const char* value()
  {
    return DataType< ::atwork_commander_msgs::StartTask >::value();
  }
  static const char* value(const ::atwork_commander_msgs::StartTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_STARTTASK_H
