// Generated by gencpp from file atwork_commander_msgs/StartTaskResponse.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_STARTTASKRESPONSE_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_STARTTASKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct StartTaskResponse_
{
  typedef StartTaskResponse_<ContainerAllocator> Type;

  StartTaskResponse_()
    : end()
    , error()  {
    }
  StartTaskResponse_(const ContainerAllocator& _alloc)
    : end()
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _end_type;
  _end_type end;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartTaskResponse_

typedef ::atwork_commander_msgs::StartTaskResponse_<std::allocator<void> > StartTaskResponse;

typedef boost::shared_ptr< ::atwork_commander_msgs::StartTaskResponse > StartTaskResponsePtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::StartTaskResponse const> StartTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.end == rhs.end &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "466c3d57e5221d6c6ec7f14172c754e3";
  }

  static const char* value(const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x466c3d57e5221d6cULL;
  static const uint64_t static_value2 = 0x6ec7f14172c754e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/StartTaskResponse";
  }

  static const char* value(const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time end\n"
"string error\n"
"\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.end);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atwork_commander_msgs::StartTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "end: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.end);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_STARTTASKRESPONSE_H
