// Generated by gencpp from file atwork_commander_msgs/Task.msg
// DO NOT EDIT!


#ifndef ATWORK_COMMANDER_MSGS_MESSAGE_TASK_H
#define ATWORK_COMMANDER_MSGS_MESSAGE_TASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <atwork_commander_msgs/RobotHeader.h>
#include <atwork_commander_msgs/Workstation.h>
#include <atwork_commander_msgs/Workstation.h>

namespace atwork_commander_msgs
{
template <class ContainerAllocator>
struct Task_
{
  typedef Task_<ContainerAllocator> Type;

  Task_()
    : execute_on()
    , arena_start_state()
    , arena_target_state()
    , prep_time()
    , exec_time()
    , type()
    , id(0)  {
    }
  Task_(const ContainerAllocator& _alloc)
    : execute_on(_alloc)
    , arena_start_state(_alloc)
    , arena_target_state(_alloc)
    , prep_time()
    , exec_time()
    , type(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >::other >  _execute_on_type;
  _execute_on_type execute_on;

   typedef std::vector< ::atwork_commander_msgs::Workstation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::atwork_commander_msgs::Workstation_<ContainerAllocator> >::other >  _arena_start_state_type;
  _arena_start_state_type arena_start_state;

   typedef std::vector< ::atwork_commander_msgs::Workstation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::atwork_commander_msgs::Workstation_<ContainerAllocator> >::other >  _arena_target_state_type;
  _arena_target_state_type arena_target_state;

   typedef ros::Duration _prep_time_type;
  _prep_time_type prep_time;

   typedef ros::Duration _exec_time_type;
  _exec_time_type exec_time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef uint64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::atwork_commander_msgs::Task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atwork_commander_msgs::Task_<ContainerAllocator> const> ConstPtr;

}; // struct Task_

typedef ::atwork_commander_msgs::Task_<std::allocator<void> > Task;

typedef boost::shared_ptr< ::atwork_commander_msgs::Task > TaskPtr;
typedef boost::shared_ptr< ::atwork_commander_msgs::Task const> TaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atwork_commander_msgs::Task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atwork_commander_msgs::Task_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atwork_commander_msgs::Task_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::Task_<ContainerAllocator2> & rhs)
{
  return lhs.execute_on == rhs.execute_on &&
    lhs.arena_start_state == rhs.arena_start_state &&
    lhs.arena_target_state == rhs.arena_target_state &&
    lhs.prep_time == rhs.prep_time &&
    lhs.exec_time == rhs.exec_time &&
    lhs.type == rhs.type &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atwork_commander_msgs::Task_<ContainerAllocator1> & lhs, const ::atwork_commander_msgs::Task_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atwork_commander_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::Task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atwork_commander_msgs::Task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::Task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atwork_commander_msgs::Task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::Task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atwork_commander_msgs::Task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atwork_commander_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23084b379239948be639bf4f943f476b";
  }

  static const char* value(const ::atwork_commander_msgs::Task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23084b379239948bULL;
  static const uint64_t static_value2 = 0xe639bf4f943f476bULL;
};

template<class ContainerAllocator>
struct DataType< ::atwork_commander_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atwork_commander_msgs/Task";
  }

  static const char* value(const ::atwork_commander_msgs::Task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atwork_commander_msgs::Task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Task.msg\n"
"\n"
"RobotHeader[] execute_on\n"
"\n"
"Workstation[] arena_start_state\n"
"Workstation[] arena_target_state\n"
"\n"
"duration prep_time\n"
"duration exec_time\n"
"\n"
"string type\n"
"uint64 id\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/RobotHeader\n"
"# RobotHeader.msg\n"
"\n"
"Header header\n"
"string team_name\n"
"string robot_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Workstation\n"
"# workstation.msg\n"
"\n"
" Object[] objects\n"
"\n"
"# either a workstation name or 'robot'\n"
"# (for end of RTT or start of PPT)\n"
"string workstation_name\n"
"\n"
"================================================================================\n"
"MSG: atwork_commander_msgs/Object\n"
"# Object.msg\n"
"\n"
"uint16 object\n"
"uint16 target\n"
"bool   decoy\n"
"\n"
"uint16 EMPTY = 0\n"
"\n"
"# atwork\n"
"uint16 ATWORK_START = 11\n"
"uint16 F20_20_B = 11\n"
"uint16 F20_20_G = 12\n"
"uint16 S40_40_B = 13\n"
"uint16 S40_40_G = 14\n"
"uint16 M20_100 = 15\n"
"uint16 M20 = 16\n"
"uint16 M30 = 17\n"
"uint16 R20 = 18\n"
"uint16 ATWORK_END = 19\n"
"\n"
"# rockin\n"
"uint16 ROCKIN_START = 21\n"
"uint16 BEARING_BOX = 21\n"
"uint16 BEARING = 22\n"
"uint16 AXIS = 23\n"
"uint16 DISTANCE_TUBE = 24\n"
"uint16 MOTOR = 25\n"
"uint16 ROCKIN_END = 26\n"
"\n"
"# container\n"
"uint16 CONTAINER_START = 31\n"
"uint16 CONTAINER_RED = 31\n"
"uint16 CONTAINER_BLUE = 32\n"
"uint16 CONTAINER_END = 33\n"
"\n"
"# cavity\n"
"uint16 CAVITY_START = 41\n"
"uint16 F20_20_H  = 41\n"
"uint16 F20_20_V  = 42\n"
"uint16 F20_20_F  = 43\n"
"uint16 S40_40_H  = 44\n"
"uint16 S40_40_V  = 45\n"
"uint16 S40_40_F  = 46\n"
"uint16 M20_H     = 47\n"
"uint16 M20_V     = 48\n"
"uint16 M20_F     = 49\n"
"uint16 M20_100_H = 50\n"
"uint16 M20_100_V = 51\n"
"uint16 M20_100_F = 52\n"
"uint16 M30_H     = 53\n"
"uint16 M30_V     = 54\n"
"uint16 M30_F     = 55\n"
"uint16 R20_H     = 56\n"
"uint16 R20_V     = 57\n"
"uint16 R20_F     = 58\n"
"uint16 CAVITY_END = 59\n"
;
  }

  static const char* value(const ::atwork_commander_msgs::Task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atwork_commander_msgs::Task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute_on);
      stream.next(m.arena_start_state);
      stream.next(m.arena_target_state);
      stream.next(m.prep_time);
      stream.next(m.exec_time);
      stream.next(m.type);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atwork_commander_msgs::Task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atwork_commander_msgs::Task_<ContainerAllocator>& v)
  {
    s << indent << "execute_on[]" << std::endl;
    for (size_t i = 0; i < v.execute_on.size(); ++i)
    {
      s << indent << "  execute_on[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::atwork_commander_msgs::RobotHeader_<ContainerAllocator> >::stream(s, indent + "    ", v.execute_on[i]);
    }
    s << indent << "arena_start_state[]" << std::endl;
    for (size_t i = 0; i < v.arena_start_state.size(); ++i)
    {
      s << indent << "  arena_start_state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::atwork_commander_msgs::Workstation_<ContainerAllocator> >::stream(s, indent + "    ", v.arena_start_state[i]);
    }
    s << indent << "arena_target_state[]" << std::endl;
    for (size_t i = 0; i < v.arena_target_state.size(); ++i)
    {
      s << indent << "  arena_target_state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::atwork_commander_msgs::Workstation_<ContainerAllocator> >::stream(s, indent + "    ", v.arena_target_state[i]);
    }
    s << indent << "prep_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.prep_time);
    s << indent << "exec_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.exec_time);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATWORK_COMMANDER_MSGS_MESSAGE_TASK_H
